pipeline {
        agent any
        
        tools{
                maven 'Maven'
        }
        stages{
            stage('clean'){
                steps {
                 echo "clean project"
                 bat "mvn clean"

                }
            }
            stage('Test'){
                steps{ 
                 echo "test project"
                 bat "mvn test"
                        
                }
            }
            stage('build'){
                steps {
                 echo "Deploy project"
                 bat "mvn deploy"
     
                        
                }
            }
        }
}

